### PR TITLE
app-alarm-ui Automated Actions Gui enhancement suggestion

### PR DESCRIPTION
**Pull request by katysaintin**
By replacing simple Textfield detail column by 2 columns :

    A combobox to select email , cmd or sevrpv
    A textfield to define the information ( email  command pvname )

The detail property will built as following option:info
See the following screenshot to see the difference
AutomateActionsSuggestion

One classe modified 
https://github.com/katysaintin/phoebus/blob/master/app/alarm/ui/src/main/java/org/phoebus/applications/alarm/ui/tree/TitleDetailDelayTable.java

### CODE REVIEW

**Comment by kasemir** [comment]
Can you keep the change to just TitleDetailDelayTable , without the pom.xml changes?

**Comment by katysaintin** [comment]
> Can you keep the change to just TitleDetailDelayTable , without the pom.xml changes?

Yes of course. I will suggest another modification by replacing TextField editor for the delay by a Spinner.

**Comment by kasemir** [comment]
Looks good. Will wait for the test build to complete, then merge

**Comment by katysaintin** [comment]
Now it's seems to be OK.

**Pull request merged**
