### PR TITLE
#1753 moving dialog to core-ui, adding javadocs, ui demo

### PR DESCRIPTION
**Pull request by shroffk**
I think this dialog might be useful in other places too
image

### CODE REVIEW

**Comment by kasemir** [comment]
Maybe use the shared up/down images, `JFXUtil.getIcon("up.png")`, `JFXUtil.getIcon("down.png")`?

Screen Shot 2021-01-28 at 12 59 13 PM


Those are using the up.png and down.png from the Eclipse icons.
Could look for left/right icons, or in a pinch create them by rotating the up/down images in an image editor.

**Comment by shroffk** [comment]
image

**Comment by kasemir** [comment]
Does double-clicking on an available option add it, and double-clicking on already added option remove it?

**Comment by kasemir** [comment]
.. Looks like the code contains double-click handlers that move left/right, good!

**Pull request merged**
