### PR TITLE
Create GitHub Actions workflows

### PR DESCRIPTION
**Pull request by andersharrisson-ess**
Github Actions workflows that builds and publishes Phoebus onto ESS Artifactory.
This PR requires credentials for Artifactory to be set in Github Secrets.

### CODE REVIEW

**Comment by shroffk** [comment]
@andersharrisson-ess I have given you permissions to manage this repo... you can add the necessary secrets

**Comment by andersharrisson-ess** [comment]
Thank you,
I have added the required credentials now.
The Github Actions workflows, if you choose to merge them, triggers build and publish to Artifactory for all commits pushed to master branch as well as tags. One caveat is that you must not push (or tag) a commit with release versions twice. The second workflow will fail since overwriting versions in Artifactory is not allowed.
Pull-requests (to all branches) as well as pushed commits to non-master branches will just trigger a "mvn package" - not a publish to Artifactory.

**Comment by andersharrisson-ess** [comment]
This PR introduces an alternative to travis-ci, so obviously there is overlapping functionality. If you decide to move onto Github Actions, the .travis.yml should be removed once the Github Actions workflows have been verified.

**Comment by andersharrisson-ess** [comment]
Thank you for the merge, @shroffk 
I can see that artifacts are being correctly pushed from Github Actions to ESS Artifactory now. You can safely remove the .gitlab-ci.yml file, since we no longer need our own CI at ESS.

**Pull request merged**
