### PR TITLE
Avoids NullPointerException when shutting down PVAServer

### PR DESCRIPTION
**Pull request by jacomago**

### CODE REVIEW

**Comment by kasemir** [comment]
How do you get a null pointer exception there?
`server` is private final, initialized in the constructor.
https://github.com/ControlSystemStudio/phoebus/blob/9f9957bfb1cca3fe6f20ce6f809c675d2b14a213/core/pva/src/main/java/org/epics/pva/server/ServerTCPHandler.java#L65
Maybe instead change that to
```
 public ServerTCPHandler(final PVAServer server, final Socket client, final TLSHandshakeInfo tls_info) throws Exception
 {
        super(client, false);
        this.server = Objects.requireNonNull(server);
```

**Comment by jacomago** [comment]
Stack trace is 

```
15-Nov-2023 14:57:49.063 WARNING [Thread-16] org.epics.pva.common.TCPHandler.close Cannot stop receive thread
	java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.epics.pva.server.PVAServer.shutdownConnection(org.epics.pva.server.ServerTCPHandler)" because "this.server" is null
		at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
		at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
		at org.epics.pva.common.TCPHandler.close(TCPHandler.java:557)
		at org.epics.pva.server.PVAServer.close(PVAServer.java:262)
		at org.epics.archiverappliance.retrieval.pva.PvaDataRetrievalServlet.destroy(PvaDataRetrievalServlet.java:57)
		at org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1258)
		at org.apache.catalina.core.StandardWrapper.stopInternal(StandardWrapper.java:1544)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:242)
		at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5135)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:242)
		at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1348)
		at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1337)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
		at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:931)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:242)
		at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1348)
		at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1337)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
		at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:931)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:242)
		at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:496)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:242)
		at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:973)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:242)
		at org.apache.catalina.startup.Catalina.stop(Catalina.java:849)
		at org.apache.catalina.startup.Catalina$CatalinaShutdownHook.run(Catalina.java:996)
	Caused by: java.lang.NullPointerException: Cannot invoke "org.epics.pva.server.PVAServer.shutdownConnection(org.epics.pva.server.ServerTCPHandler)" because "this.server" is null
		at org.epics.pva.server.ServerTCPHandler.onReceiverExited(ServerTCPHandler.java:125)
		at org.epics.pva.common.TCPHandler.receiver(TCPHandler.java:317)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
		at java.base/java.lang.Thread.run(Thread.java:1583)
```

Looks like calling PVAServer.close() creates some futures to call ServerTCPHandler.onReceiverExited which don't run until the server is already null. Maybe a different solution is needed?

**Review by kasemir — APPROVED** [review]
That looks good. Do you now capture null being passed in for the server?

**Comment by jacomago** [comment]
@kasemir  Still getting a problem:


```
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.epics.pva.server.PVAServer.shutdownConnection(org.epics.pva.server.ServerTCPHandler)" because "this.server" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.epics.pva.common.TCPHandler.close(TCPHandler.java:562)
	at org.epics.pva.server.PVAServer.close(PVAServer.java:272)
	at org.epics.archiverappliance.retrieval.pva.PvaDataRetrievalServlet.destroy(PvaDataRetrievalServlet.java:57)
	at org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1258)
	at org.apache.catalina.core.StandardWrapper.stopInternal(StandardWrapper.java:1544)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:242)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5135)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:242)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1348)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1337)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:931)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:242)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1348)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1337)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:931)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:242)
	at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:496)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:242)
	at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:973)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:242)
	at org.apache.catalina.startup.Catalina.stop(Catalina.java:849)
	at org.apache.catalina.startup.Catalina$CatalinaShutdownHook.run(Catalina.java:996)
Caused by: java.lang.NullPointerException: Cannot invoke "org.epics.pva.server.PVAServer.shutdownConnection(org.epics.pva.server.ServerTCPHandler)" because "this.server" is null
	at org.epics.pva.server.ServerTCPHandler.onReceiverExited(ServerTCPHandler.java:145)
	at org.epics.pva.common.TCPHandler.receiver(TCPHandler.java:322)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by jacomago** [comment]
Maybe it's because I have several PVAServer s running. And another has been shut down just before.

**Comment by kasemir** [comment]
Well, in the constructor we do this:
```
public ServerTCPHandler(final PVAServer server, final Socket client, final TLSHandshakeInfo tls_info) throws Exception
{
    super(client, false);
    this.server = Objects.requireNonNull(server);
```

From then on, 'server' is non-null and cannot be changed.
Still, you find it null in `onReceiverExited(final boolean running)`.
That could be happening because the `super(client, ...` call in the constructor ends up invoking `onReceiverExited` before the constructor gets a chance to set `this.server = server`.

The fix should be something along the lines of the already existing TCPHandler.startSender. Just like we start the sender explicitly after construction, the TCPHandler constructor should _not_ submit `this::receiver` to the threadpool to start a receive thread, but do that in an explicit startReceiver that's called after construction.

I'll look at that.
Do you have a standalone demo of the error, outside of some archive appliance service?

**Comment by kasemir** [comment]
See alternate PR #2872:

TCPHandler no longer starts the receive_thread, so `onReceiverExited` can no longer emitted early.

Client and ServerTCPHandler explicitly `startReceiver()` after they're fully constructed and for example `server` is set. For good measure added some `requireNonNull` checks, but it looks like those were always non-null, just a matter of starting the receiver thread too early.

That still works for me with simple tests, maybe you can try within the archive appliance.

**Comment by jacomago** [comment]
Close for alternate PR #2872

**Pull request closed without merging**
