### PR TITLE
add back in vtable conversion removed by mistake

### PR DESCRIPTION
**Pull request by jembishop**
The functionality to convert vTables got removed by accident in the refactor.
Reinstated this functionality.

### CODE REVIEW

**Review by georgweiss — COMMENTED** [review]
This is fine provided you add to the pom.xml:
```
<dependency>
      <groupId>org.phoebus</groupId>
      <artifactId>core-pva</artifactId>
      <version>4.7.4-SNAPSHOT</version>
    </dependency>
```

**Comment by georgweiss** [comment]
@jembishop, the addition of  ```core-pv```  causes  acyclic dependency. Only ```core-pva``` is needed.

Also, the ```UtiltiesTest``` class needs an update as som static methods have moved.

**Comment by jembishop** [comment]
@georgweiss Thanks for your help resolving my issues, I think it is good to merge now.

**Comment by georgweiss** [comment]
Yes, looks fine, runs as expected.

**Pull request merged**
