### PR TITLE
#1561

### PR DESCRIPTION
**Pull request by shroffk**
Alarm datasource with special fields

### CODE REVIEW

**Comment by georgweiss** [comment]
Took this for a spin and spotted some issues.
1) Use the various fields (state, active, enabled) works if used only once, i.e. an OPI containing widgets for all of them will update only one widget. Seems ordering is a factor: only the widget connecting last will update. Can be verified using separate OPIs for each of the fields.
2) The duration field - when bound to a text update - looks disconnected and always shows NaN.
3) Writing enable/disable seems to work and is reflected in the alarm tree. However, the issue described in 1) will potentially result in a LED showing the enabled field to not update.

**Comment by shroffk** [comment]
Looking into point 1. first

**Comment by shroffk** [comment]
Ok, There is a bug in the pv registration when there is one of these special fields used. It does affect updates to other pvs from the datasources too. I will fix this before we merge this PR

**Comment by shroffk** [comment]
@georgweiss thanks for testing...
Since both `alarm://root/path/node` and `alarm://root/path/node.state` both register to the same node `/root/path/node`.
There was conflict where the new connection was replace the old.

The new implementation maintains a list for both the above cases

**Comment by georgweiss** [comment]
Works fine now. My test of duration was wrong, so what I can see now is the time stamp of the last alarm state transition.
Also tested ack/unack, and it works fine.

**Review by georgweiss — APPROVED** [review]
Works as expected.

**Pull request merged**
