### PR TITLE
expanding support for types of values set-able on macro properties #3108

### PR DESCRIPTION
**Pull request by shroffk**

### CODE REVIEW

**Review by kasemir — COMMENTED** [review]
`instance Map` just checks if it's a Map.
We cannot know for sure that it's a `Map<String, String>`.
Might be a map of objects.

All that could still be handled via something like
```
private static Macros fromMap(Map<Object, Object> names_and_values)
...
names_and_values.entrySet().forEach(
   e -> macros.add(Objects.toString(e.getKey()),
                   Objects.toString(e.getValue())));
```

**Comment by shroffk** [comment]
Actually, I was planning on just throwing an exception.
`Objects.toString` might not result in anything very useful if it isn't a String.

but.. I am fine with your suggestion too

**Comment by kasemir** [comment]
When called from Jython, I'm not exactly sure what you get.
Could be some `Map<PyString, PyString>` type.

Since you proposed handling maps from a script, I assume you have a test script to try this, so check if casting to `Map<String, String>` works.
Throwing an exception for other types is fine as well.

**Comment by shroffk** [comment]
The existing scripts I have are javascripts ( and the more I work on this the more I believe we should not be using scripting )

However the good thing is that the scripts uses `DataUtil.createMacrosInput` which gives a Map<String, String>

I tested with a Map<Object, Object> and we basically would have a cast except when trying to access a key or value that was not a String.

I have decided to go with your suggestion since it can potentially support things like a Map<String, Integer> with example being 
Cell=22

**Comment by shroffk** [comment]
Note:
This should be another example for why to avoid scripts

**Pull request merged**
