### PR TITLE
Display editor: Pass exception from "Save As" up to trigger error dlg

### PR DESCRIPTION
**Pull request by kasemir**
#1544

### CODE REVIEW

**Comment by georgweiss** [comment]
Thanks, this fixes the issue.
However, in the case  when user closes the application and is prompted to save if a dirty file is open. Currently the applications does not close after the file has been saved, even though that was the user's intention. Should this behavior be maintained?

**Comment by kasemir** [comment]
I'll look at that.

**Comment by pavel-ch** [comment]
Yes I also vote for changing this. Now, if a changed file is somewhere in the middle of your open tabs, the first bunch of tabs closes, then Phoebus asks for saving and stops closing. After you close the Phoebus then, and start again, you get your workplace back with the half of originally open tabs. This is not a bug, but it is really annoying.

**Comment by kasemir** [comment]
I'm working on it.
The technical problem is that we only had a `boolean` is-ok-to-close check.
For a 'clean' tab it can return 'true' and you close the tab.
For a 'dirty' tab it had to return 'false' right now to keep the tab open and then start the process of saving.
The result was that all the clean tabs close, the dirty ones stay open, and the app remains open after all is saved.

In the update, it uses a `Future<Boolean>` is-ok-to-close check. That way, "close" can start a background thread for checking all the tabs, await their answer (which could be 'ok' after some delay for saving the file, or 'no' after some delay if saving failed), and then process to close once all are 'ok'.

Overall, this looks much better: "Close" will first prompt "Do you want to save?" etc., and then close everything down.
But it will take another day to test all the scenarios.

**Comment by pavel-ch** [comment]
In practice, this change is working quite fine, but:
In DisplayRuntime, looks like with this change, I am getting exceptions when closing display via script ScriptUtil.closeDisplay(widget):
```
2020-10-09 12:18:14 SEVERE [org.phoebus.ui.docking] Failed to call prepareToClose
java.lang.Exception: Stack Trace
	at org.phoebus.ui.docking.DockItem.close(DockItem.java:651)
	at org.csstudio.display.builder.runtime.app.DisplayRuntimeInstance.close(DisplayRuntimeInstance.java:258)
	at org.csstudio.display.builder.runtime.app.DockItemRepresentation.lambda$0(DockItemRepresentation.java:143)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
because DockItem prepareToClose() has not been called before. In the runtime, we usually do not need a dirty state check, so the question is whether there should be an option to close intentionally without the "prepareToClose()" call. This is done anyway now, but with the side effect of the above Exception logged.

**Comment by kasemir** [comment]
While the message looks SEVERE, the closing does continue just fine. End users won't see it.
Since the script is calling `ScriptUtil.closeDisplay`, it should be easy enough to update the `ScriptUtil` to perform the complete `prepareToClose`-then-`close` cycle, which will silence that message.

**Comment by pavel-ch** [comment]
That is not that easy due to threading issues, both`ScriptUtil.closeDisplay` which is calling `DockItemRepresentation.closeWindow(DisplayModel)`do not know DockItem. Then DisplayRuntimeInstance.close() gets called in UI thread, but prepareToClose cannot be used there being on UI thread. Any idea?

**Comment by kasemir** [comment]
I don't see a fundamental issue. Yes, ScriptUtil, i.e. the runtime, doesn't know the dock item, but the toolkit which is asked to actually perform the 'close' does. I'll work on it.

**Comment by pavel-ch** [comment]
Yes principally that must be trivial, I only hesitated where to place the `prepareToClose` call. Thanks.

**Pull request merged**
