### PR TITLE
CSSTUDIO-1131: tab/shift-tab navigation between elements/nodes in widget color property popover

### PR DESCRIPTION
**Pull request by cjenkscybercom**
This feature enables tab/shift-tab navigation in color property popovers in the Display Editor.
The below image illustrates this, the exception being there is navigation between the search text field and Red spinner to the Color colorpicker field.
Screenshot 2022-09-13 at 10 40 30

### CODE REVIEW

**Review by kasemir — APPROVED** [review]
Looks good. Does this then require #2383, without the TAB support #2383 was fine?

**Comment by kasemir** [comment]
>  the changes are independent from each other

..  git begs to differ ;-)

**Comment by cjenkscybercom** [comment]
> > the changes are independent from each other
> 
> .. git begs to differ ;-)

hah ;)
I meant functionally, doh

**Comment by kasemir** [comment]
Right. Mean what you say and say what is mean!
Wait, that doesn't sound right?!

**Pull request merged**
