### PR TITLE
WIP: address a group of alarm logging service and application issues

### PR DESCRIPTION
**Pull request by shroffk**
#2068 
#2072 
#2074 
Resolved

working on matching changes for #2069

### CODE REVIEW

**Comment by shroffk** [comment]
Additionally,
I also standardized the elastic client dependency - all services and client now are using 6.8.4
Using a single property, `es.version` ( like a lot of other dependency groups )

**Review by kasemir — COMMENTED** [review]
While this updates `create_alarm_index.sh` to use `?include_type_name=true` in the URLs for Elastic version 7, there's now also code related to `alarms_*_template.json` which has the logger automagically install the templates.
Should the `create_alarm_index.sh` just be removed, it's no longer necessary? And update the README.md to also not mention it?

**Comment by shroffk** [comment]
@kasemir I am fine with deleting the startup scripts.. .I just wasn't sure if anyone is using them in the deployment process.
I will poll people on Wednesday and then delete it, along with updating the readme.md

I tested the new programmatic way of creating the templates on elastic 6.8.4 and elastic 7.15.2.. it created the templates on both versions.

@tanviash @georgweiss are you guys fine with simply deleting the create scripts?

**Comment by tanviash** [comment]
> @tanviash @georgweiss are you guys fine with simply deleting the create scripts?
Yes, deleting it is fine by me.

**Review by georgweiss — COMMENTED** [review]
If the scripts are not need to setup the service, then I'm fine with removing them.

**Comment by shroffk** [comment]
- Colour coding the severity columns
 - Adding a new column which displays time deltas
 - Enable selection of column to be displayed.

image

**Review by georgweiss — COMMENTED** [review]
Columns selection will be appreciated. Propose to add the same in the alarm table view. 
Is the selection persisted in memento and loaded on initialization?

**Pull request merged**
