### PR TITLE
Split dock unit test

### PR DESCRIPTION
**Pull request by lorenzo-gomez-windhover**
Hi there,

Hope you are all doing well.

These unit tests use TestFX's Robot API to test the behavior of `DockPane` and `SplitDock` classes. Specifically these unit tests test the behavior discussed in  #1986 and  #1991.

I know GUI testing can be tricky because it might very well behave differently on different platforms, but I tried my best to write these tests in a platform-independent way. By all means try it in other platforms as I ran the test only on `Ubuntu 18.04.5 LTS`. It is possible I missed something, but hopefully these tests are reliable enough that we can trust them when it comes to GUI testing.

Thanks
Lorenzo

### CODE REVIEW

**Comment by georgweiss** [comment]
Running ``mvn clean install`` on Mac will hang the build at SplitDockTest.
Running the test from IntelliJ succeeds, but there are exceptions:

``
WARNING: Cannot set application icon
java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:276)
	at org.phoebus.framework.workbench.Locations.install(Locations.java:83)
	at org.phoebus.ui.docking.DockStage.getLogo(DockStage.java:79)
	at org.phoebus.ui.docking.DockStage.configureStage(DockStage.java:146)
	at org.phoebus.ui.docking.SplitDockTest.start(SplitDockTest.java:44)
	at org.testfx.framework.junit.ApplicationAdapter.start(ApplicationAdapter.java:40)
	at org.testfx.toolkit.impl.ApplicationServiceImpl.lambda$start$0(ApplicationServiceImpl.java:51)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
``

**Comment by kasemir** [comment]
Again I think we need a naming convention or related mechanism to distinguish UI tests.
In #314, Kunal suggested `...UI` for "interface tests using testFX".
Maybe rename `SplitDockTest` into `SplitDockUI` so it's not automatically invoked by the headless build which has problems executing UI tests?

**Comment by lorenzo-gomez-windhover** [comment]
> Maybe rename `SplitDockTest` into `SplitDockUI` so it's not automatically invoked by the headless build which has problems executing UI tests?

@kasemir  So does the CI ignore any tests that end in `*UI`? If that is the case, I can always rename the test.

**Comment by kasemir** [comment]
Better ask anyone but me about maven...
In #314, Kunal suggested ..UI for UI tests, and he also mentioned using surefire for running tests.
As I read the surefire doc, https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html, these are automatically executed:
```
By default, the Surefire Plugin will automatically include all test classes with the following wildcard patterns:
"**/Test*.java" - includes all of its subdirectories and all Java filenames that start with "Test".
"**/*Test.java" - includes all of its subdirectories and all Java filenames that end with "Test".
"**/*Tests.java" - includes all of its subdirectories and all Java filenames that end with "Tests".
"**/*TestCase.java" - includes all of its subdirectories and all Java filenames that end with "TestCase".
```

I assume that was part of the reason for suggesting ..UI for UI tests, so by default they would be skipped.

**Comment by lorenzo-gomez-windhover** [comment]
I renamed my tests to `DockPaneTestUI` and `SplitDockTestUI` and they are skipped.

**Comment by shroffk** [comment]
@kasemir thank you for digging through the issues and finding that.
I think we should move this to read the docs... I am thinking a section under the "for developers".
I know in the past we have had divergence in opinions about code styles, but despite that we have a lot of agreement... like class names, test names, organization of modules, design patterns etc... which we should start documenting and leave out the things we don't yet have consensus on.

**Comment by shroffk** [comment]
@lorenzo-gomez-windhover we tend to have monthly meeting to share new developments or issues, if you are interested in attending let me know.

**Comment by lorenzo-gomez-windhover** [comment]
@shroffk  Yes, I I'd love to! How can I join the meeting?

**Comment by shroffk** [comment]
Can this PR be merged.

@lorenzo-gomez-windhover we meet using google hangouts, I will add you to the next meeting :)

**Comment by georgweiss** [comment]
I do not mind as long as Maven builds are fine.

**Comment by shroffk** [comment]
@lorenzo-gomez-windhover I do not have an email address to forward the monthly meeting invitation.
You can email me at kunalshroff9@gmail.com and I will add you to the meeting list.

**Pull request merged**
