### PR TITLE
Support for opening save&restore resource

### PR DESCRIPTION
**Pull request by georgweiss**
Changes in this PR:

1. Save & restore made into a "singleton" instance, i.e. opened only once.
2. Added support for opening with resource, e.g. file:/<unique_node_id>?app=saveandrestore. This can be used by Olog properties, i.e. an entry automatically created from a restore context can add the resource identifier thus enabling launch of save & restore from log viewer.
3. Minor bug fix in context menu.

### CODE REVIEW

**Comment by shroffk** [comment]
What would happen is ```app=saveandrestore``` is missing when launching the resource

**Comment by georgweiss** [comment]
Then the framework will log that no application was found to handle the "file", and Save & Restore will not be launched unless it is restored from ~/.phoebus.

Actually I'd prefer an API to find application based on scheme, say saveandrestore:/resource-id.

**Comment by shroffk** [comment]
Oh no...
We now have conflicts

**Comment by georgweiss** [comment]
Will fix merge conflict...

**Comment by georgweiss** [comment]
Merge conflicts resolved.

**Pull request merged**
