### PR TITLE
Csstudio 1215: Transparency Support for ProgressBar, SlideButton, ComboBox widgets

### PR DESCRIPTION
**Pull request by cjenkscybercom**
Adds support for transparency to the ProgressBar, SlideButton, ComboBox widgets

### CODE REVIEW

**Comment by georgweiss** [comment]
@kasemir, would appreciate your input on this.

**Comment by kasemir** [comment]
I already commented on the removal of the "SmallBar" setting.
We have screens where many bars are stacked next to each other, each just say 10 pixels wide.
Without switching to "SmallBar", those bars basically vanish since they become all outline, no content.
Unclear why it was removed.
Maybe attach screenshots of small bars (10 pixel wide) before and after this change to check the impact.

**Comment by cjenkscybercom** [comment]
> I already commented on the removal of the "SmallBar" setting. We have screens where many bars are stacked next to each other, each just say 10 pixels wide. Without switching to "SmallBar", those bars basically vanish since they become all outline, no content. Unclear why it was removed. Maybe attach screenshots of small bars (10 pixel wide) before and after this change to check the impact.

Hi Kay, I don't see those comments here. Can you please elaborate / clarify how this relates to the alpha/transparency changes? 

Thanks!

**Comment by kasemir** [comment]
> Can you please elaborate / clarify how this relates to the alpha/transparency changes?

Exactly!

I was surprised that you removed the "SmallBar" style when you added transparency support.
You could have left that alone:

Screenshot 2023-02-07 at 9 41 35 AM

**Comment by kasemir** [comment]
Since the "review" feature doesn't seem to work, see screenshot of the review in last message

**Comment by cjenkscybercom** [comment]
> > Can you please elaborate / clarify how this relates to the alpha/transparency changes?
> 
> Exactly!
> 
> I was surprised that you removed the "SmallBar" style when you added transparency support. You could have left that alone:
> 
> Screenshot 2023-02-07 at 9 41 35 AM

Hi Kay,

Looks like that line was already commented out / unused, so I probably removed it as part of cleaning up the surrounding code. Would explain why I didn't recognize it...

Do we want to leave that in as it was then (as a comment)?

**Comment by kasemir** [comment]
> was already commented out / unused

??

Your commit commented it out.
Right now, https://github.com/ControlSystemStudio/phoebus/blob/master/app/display/representation-javafx/src/main/java/org/csstudio/display/builder/representation/javafx/widgets/ProgressBarRepresentation.java looks like this:

```
            // Default 'inset' of .bar uses 7 pixels.
            // A widget sized 15 has 8 pixels left for the bar.
            // Select leaner style where .bar uses full size.
            Styles.update(jfx_node, "SmallBar",
                          Math.min(width, height) <= 15);
```


Screenshot 2023-02-07 at 9 54 10 AM

**Comment by cjenkscybercom** [comment]
> > was already commented out / unused
> 
> ??
> 
> Your commit commented it out. Right now, https://github.com/ControlSystemStudio/phoebus/blob/master/app/display/representation-javafx/src/main/java/org/csstudio/display/builder/representation/javafx/widgets/ProgressBarRepresentation.java looks like this:
> 
> ```
>             // Default 'inset' of .bar uses 7 pixels.
>             // A widget sized 15 has 8 pixels left for the bar.
>             // Select leaner style where .bar uses full size.
>             Styles.update(jfx_node, "SmallBar",
>                           Math.min(width, height) <= 15);
> ```
> 
> Screenshot 2023-02-07 at 9 54 10 AM

Hi, 

I might have read the information backwards on the PR. Regardless, it has been four months since this PR was submitted and I'll need time to re-orient myself on what this was originally about.

Thanks for your patience!

**Comment by kasemir** [comment]
It's possible that the styling sheet gymnastics for adding transparency conflicted with the "SmallBar" settings.For the ProgressBar I see tweaks to the "-fx-accent:" and "-fx-control-inner-background:". "SmallBar" is mostly about insets and padding, but also tweaks the "-fx-background-color:", maybe that's why you had to disable it??

**Comment by cjenkscybercom** [comment]
Either way, I'm glad that was caught...

I've pushed the changes, and have no idea why I would have commented that out since it has nothing to do with the alpha. I suspect it may have snuck in by accident while debugging and investigating early on when working on this.

Let me know if there's anything else!

**Comment by kasemir** [comment]
Can you quickly check "small" progress bars?

Below are two with the "default" width of 20 pixels and then two 10 pixels wide, placed side by side.
Note how the "SmallBar" removes the border which would otherwise take up most of the space as the widget gets smaller:

Screenshot 2023-02-07 at 10 51 46 AM

Ideally, that would still work the same way with your update

**Comment by kasemir** [comment]
> Can you quickly check "small" progress bars?

Never mind, just tried it out. The "small" progress bars still look good. Bars continue to transitions between the normal and the "small" look when changing bar width (or height when horizontal).
For the "small" bars, I can also make the background be transparent, and your added support for transparent works fine there.

.. but the normal bars, those that do NOT use the special "SmallBar" style, don't use transparent background.

In this screenshow, everything inside the marked section uses "transparent" background. The "small" bars indeed have one, the normal bars are plain gray:

Screenshot 2023-02-10 at 3 04 17 PM

**Comment by cjenkscybercom** [comment]
> > Can you quickly check "small" progress bars?
> 
> Never mind, just tried it out. The "small" progress bars still look good. Bars continue to transitions between the normal and the "small" look when changing bar width (or height when horizontal). For the "small" bars, I can also make the background be transparent, and your added support for transparent works fine there.
> 
> .. but the normal bars, those that do NOT use the special "SmallBar" style, don't use transparent background.
> 
> In this screenshow, everything inside the marked section uses "transparent" background. The "small" bars indeed have one, the normal bars are plain gray:
> 
> Screenshot 2023-02-10 at 3 04 17 PM

Screenshot 2023-02-15 at 09 06 14
218187545-41b8e30e-e316-4fe4-84bc-7004fdabe60a.png)

Screenshot 2023-02-15 at 09 07 13

**Comment by kasemir** [comment]
[PBars.bob.txt](https://github.com/ControlSystemStudio/phoebus/files/10743590/PBars.bob.txt)

See attachment for example. The "transparent" ones simply have the background color alpha set to zero, so the rest of the RGB values shouldn't matter.

Screenshot 2023-02-15 at 8 46 34 AM

The narrow ones which internally switch to the "SmallBar" style have a transparent background as expected, while the wider ones have a gray background. When I change the background to say red with alpha zero, they still show the gray background...

Not sure what we do about this. If you're happy with the handling of transparency/alpha, and I'm happy with the handling of small progress bars ("SmallBar" style), and considering that "normal" progress bars without alpha in the background look like before, we can declare this perfect and merge.

**Comment by cjenkscybercom** [comment]
> [PBars.bob.txt](https://github.com/ControlSystemStudio/phoebus/files/10743590/PBars.bob.txt)
> 
> See attachment for example. The "transparent" ones simply have the background color alpha set to zero, so the rest of the RGB values shouldn't matter.
> 
> Screenshot 2023-02-15 at 8 46 34 AM
> 
> The narrow ones which internally switch to the "SmallBar" style have a transparent background as expected, while the wider ones have a gray background. When I change the background to say red with alpha zero, they still show the gray background...
> 
> Not sure what we do about this. If you're happy with the handling of transparency/alpha, and I'm happy with the handling of small progress bars ("SmallBar" style), and considering that "normal" progress bars without alpha in the background look like before, we can declare this perfect and merge.

Strange, I see a completely different result. I'm on MacOS, and I don't see those backgrounds at all.
Possibly related, you sent me a text file and Phoebus refused to open it until I used the command line to rename it. And it's now also missing some of the text that you have in your screenshot.

Screenshot 2023-02-17 at 08 37 58

I've zipped the file so I can upload it to GitHub. Maybe you could try zipping yours so we have the exact same file? (if you changed the extension so it would be uploadable, GH might have mangled it)
[PBars.bob.zip](https://github.com/ControlSystemStudio/phoebus/files/10764446/PBars.bob.zip)

**Comment by kasemir** [comment]
Yes, the *.txt needs to be removed.
Here's the diff between  the *.txt and your zipped file:

```
8c8
<     <x use_class="true">0</x>
---
>     <x use_class="true">20</x>
11c11
<     <height>31</height>
---
>     <height use_class="true">50</height>
13c13
<       <font name="Header 1" family="Liberation Sans" style="BOLD" size="22.0">
---
>       <font name="Header 1" family="Source Sans Pro" style="BOLD_ITALIC" size="36.0">
17c17
<       <color name="Text" red="0" green="0" blue="0">
---
>       <color name="HEADER-TEXT" red="0" green="0" blue="0">
20a21,23
>     <horizontal_alignment use_class="true">0</horizontal_alignment>
>     <vertical_alignment use_class="true">1</vertical_alignment>
>     <wrap_words use_class="true">false</wrap_words>
193c196
<       <font name="Header 1" family="Liberation Sans" style="BOLD" size="22.0">
---
>       <font name="Header 1" family="Source Sans Pro" style="BOLD_ITALIC" size="36.0">
```

While I'm using the default font settings, you must have "Header 1" redefined as "Source Sans Pro", a font that I don't have available locally. You also redefined the "Header 1" size as 36 instead of the default 20.
All that explains why the fonts are too small for the label sizes, and thus they get clipped in your example.
In addition, your background color used for the display must be changed to gray from the default white.

But in any case, when I open your zipped up file, "Header 1" etc. are for me back to the default definitions since I don't load a custom color or font file, and it looks like this:

Screenshot 2023-02-17 at 8 38 28 AM

So at the bottom, the small progress bars indeed have a transparent background. The larger progress bars have a gray background, which happens to match your gray background, but on top of any other color you see that they're not transparent.

**Comment by cjenkscybercom** [comment]
> 

Sorry I'm really not following. Could you send the pla file as it is, please, without renaming the extension? You'll have to zip it up to send it on GitHub. 

Please see my attached test file, it has a background color and I do not see the issues you're describing.

[alpha-test.bob.zip](https://github.com/ControlSystemStudio/phoebus/files/10988462/alpha-test.bob.zip)

**Comment by cjenkscybercom** [comment]
> [example.zip](https://github.com/ControlSystemStudio/phoebus/files/10991026/example.zip)
> 
> Screenshot 2023-03-16 at 9 04 15 AM
> 
> In this example, both of the lower progress bars are configured with the same fully transparent background. For the small one, nothing is shown because it's indeed fully transparent. For the larger one, you see a gray widget background that shouldn't be there.

Thanks for sending this,

We appear to be having an issue of "it works on my machine", as I opened your file and don't see the same problem. Could we reach out over email and do a remote screen share to figure this out?

Screenshot 2023-03-20 at 08 31 14

**Pull request merged**
