### PR TITLE
#1380 a changelog for documenting important aspects of each release

### PR DESCRIPTION
**Pull request by shroffk**
While not perfect, the goal of this changelog is to start documenting changes with each release.

The changelog is open to modification by ALL developers to add notes about API changes, features, apps, bug fixes...developers should keep appending the "current development" section.

Just before/after a release we should create a new  "current development" segment.

### CODE REVIEW

**Comment by georgweiss** [comment]
@kasemir , @krisztianloki, @pavel-ch , @geniejhang , @tanviash 
Can you please consider if there is any change that you think should go into the change log?
@shroffk, @geniejhang , where are we on the Epics core update?

**Comment by krisztianloki** [comment]
Maybe the behavior change of rules when a trigger PV is disconnected, something like:

Restore the property values of rules if a trigger PV is disconnected

**Comment by georgweiss** [comment]
@krisztianloki , IMHO that might qualify as a "minor" fix.

**Comment by krisztianloki** [comment]
These maybe:
The symbol widget now shows a semi-transparent rectangle (in front of the symbol) with the color "INVALID" when the PV is disconnected.
The LED widget shows the label when the PV is disconnected and both the "On" and "Off" labels are the same.

**Comment by georgweiss** [comment]
@krisztianloki , please submit your items into the change log.

**Comment by shroffk** [comment]
Sorry @krisztianloki beat you to it...

Just a note, 
For the time being I want to follow the system where additions to the changelog should be made by developers as they see fit without requiring approval :)...we keep the system informal and open until we find a reason to be more restrictive.

**Pull request merged**
