### PR TITLE
Add AdvancedConverter see issue #3049

### PR DESCRIPTION
**Pull request by katysaintin**
[codeathon]Add AdvancedConverter to convert massively and recursively CSS OPI to Phoebus BOB files #3049
This is an additionnal class that extends Converter class, and add corresponding Unit Tests

### CODE REVIEW

**Comment by kasemir** [comment]
Maybe add some info about the AdvancedConverter to the documentation?
All the display converter info is currently in https://github.com/ControlSystemStudio/phoebus/blob/master/app/display/convert-medm/doc/index.rst

**Comment by kasemir** [comment]
You use org.apache.commons.io.FileUtils to copy, move, read a file to string, write string to file.
That’s almost as easy with java.nio.file.Files.copy, move, Files.readString(Path.of(“…”)), Files.writeString(Path.of("..."), text).

The only difference is really the added `Path.of(...)`

**Comment by shroffk** [comment]
@katysaintin can we replace the file copy using java nio?
This would help us remove the dependency to apache commons

**Comment by katysaintin** [comment]
> @katysaintin can we replace the file copy using java nio? This would help us remove the dependency to apache commons

Yes of course,
I have to modify my code in order to remove apache commons.io dependency.
This dependency was already brought by core-ui .
So that why I thought that I can use it.

I will update my code and add rst documentation.
As @kasemir request to me.

Katy

**Comment by shroffk** [comment]
@katysaintin @lrioult Why was this PR closed?
generally this would be a feature I was hoping to include in our Phoebus

**Comment by katysaintin** [comment]
> @katysaintin @lrioult Why was this PR closed? generally this would be a feature I was hoping to include in our Phoebus

Hello @shroffk , I have ask to Léo to make a new Pullrequest , taking in account the request of Kay .
Removing commons.io dependency and adding a rst documentation.
So Now O think it's OK, I will reopen my pull request.

Sorry for this deletion, I will fix that in few minutes

**Pull request closed without merging**
