### PR TITLE
Issue #1231

### PR DESCRIPTION
**Pull request by shroffk**
Application to show display navigation

### CODE REVIEW

**Comment by kasemir** [comment]
Neat!
Can it read the model and process it in a background job?

**Comment by shroffk** [comment]
> Can it read the model and process it in a background job?

Currently it does not... I actually have a note in the javadoc's which mentions that it should be offloaded onto a different thread.

I was planning on playing with the javafx.concurrency to implement this.

**Comment by kasemir** [comment]
Alright, good.

**Comment by shroffk** [comment]
I moved the list view population off the UI thread.

For the tree view this is a little tricky, since the children are found lazily... i.e. this is when the user clicks on the node.

**Comment by shroffk** [comment]
@kasemir if you have a better suggestion for the tree solution let me know.
Otherwise I am ready to merge this.

**Comment by kasemir** [comment]
By all means go ahead and merge.
This is for people who edit/port displays.
It won't affect end users who run displays in the control room.

Not sure how to best handle the tree update on multiple threads.
For the file browser, I have 'getChildren' first return the old/empty data, since you need to return something right away. A background jobs is scheduled, which then updates the child list.

https://github.com/ControlSystemStudio/phoebus/blob/master/app/filebrowser/src/main/java/org/phoebus/applications/filebrowser/FileTreeItem.java#L64

**Comment by georgweiss** [comment]
Haven't tried his out until now, looks useful!
Just two question... In the attached screen shot the parent directory of the bob file being analyzed is listed as a child node. Intentional?
Also wonder if we should consider adding nodes representing other resources, e.g. images.
Screenshot 2020-03-25 at 10 04 23

**Comment by shroffk** [comment]
Just two question... In the attached screen shot the parent directory of the bob file being analyzed is listed as a child node. Intentional?

yes,
this is an example with cyclic links.
The root has a link to a child which has a link to the root again.

The screenshot is of a set of files I use for unit testing 🙂
________________________________

**Comment by georgweiss** [comment]
Thanks, I trie to delete the comment, it was not complete... In any case, what about also including other resources in the tree view, e.g. image files.

**Comment by shroffk** [comment]
> By all means go ahead and merge.
> This is for people who edit/port displays.
> It won't affect end users who run displays in the control room.
> 
> Not sure how to best handle the tree update on multiple threads.
> For the file browser, I have 'getChildren' first return the old/empty data, since you need to return something right away. A background jobs is scheduled, which then updates the child list.
> 
> https://github.com/ControlSystemStudio/phoebus/blob/master/app/filebrowser/src/main/java/org/phoebus/applications/filebrowser/FileTreeItem.java#L64

Thanks, 

I had tried something similar with Tasks... however in my case the 'isleaf' requires 'getChildren' to be processed. In the file browser you can check the item itself to determine 'isleaf' which is unfortunately not possible here.

I will look into other ideas.

**Comment by kasemir** [comment]
If the `isLeaf` value changes, you could still start with `isLeaf()` returning `false` and empty `getChildren()`. When the data then arrives, force a refresh via `TreeHelper.triggerTreeItemRefresh()`

**Pull request merged**
