### PR TITLE
Issue 1146 Fix for  VTypeHelper error detected i databrowser

### PR DESCRIPTION
**Pull request by georgweiss**

### CODE REVIEW

**Comment by kasemir** [comment]
I still see the same issue: Data browser sample view shows that there is data, but plot does not show a trace

db

**Comment by kasemir** [comment]
The new PlotSampleTest fails with expected 7.7 but was NaN:

db2

**Comment by georgweiss** [comment]
Works fine at my end.

**Comment by georgweiss** [comment]
Is VTypeHelper rebuilt?

**Comment by kasemir** [comment]
Turns out yes, it was a rebuild type of issue. The test now passes, and the plot also works again with both 'raw' and 'optimized' samples.

db3

Thanks!

**Pull request merged**
