### PR TITLE
Manipulating stored value cell - Issue #1242

### PR DESCRIPTION
**Pull request by geniejhang**
It's done in two ways:
1. Changing the multiplier at the right top on the screenshot.
2. Directly editing stored cell value.

So, brief explanation.
1. Changing the multiplier multiplies the number to all the non-read-only, stored values of VNumber and VNumberArray.
   - Delta values are updated accordingly as the attached.
      
    - You can also see "Save Snapshot" button is enabled. If the spinner value is not 1 or any cell has been changed from its original value by user, "(Modified)" will be added to snapshot name and tab title. In this case, by clicking "Save Snapshot" button created a new snapshot with modified values.
      
   - If you put non-number character in the spinner, it will become red and Restore button is disabled.
      

2. Changing one stored value cell behaves the same.
   - You see delta value is updated, "Save Snapshot" button is enabled, and Snapshot name and tab title have "(Modified)" at the end of them.
      

- Some comments:
   - Utilities class is updated to support unsigned type values. I don't know the frequency of those types, but anyway I added them.
   - SafeMultiply class is added to ensure multiplying number in spinner to VType value doesn't exceed its range.

Any comment is welcomed.

@georgweiss

### CODE REVIEW

**Comment by georgweiss** [comment]
Good job @geniejhang , you did what I have not had the time to realize...

One small thing: we're trying to avoid wildcard imports. Can you please update to import classes?

**Comment by geniejhang** [comment]
@georgweiss 
Sure thing. IntelliJ automatically changed all those import stuff.
I reverted those and disabled the option.

**Comment by geniejhang** [comment]
Here's the update preview.

**Comment by georgweiss** [comment]
@geniejhang , sorry for being focused on details...
We would like to support localization, so every piece of text in the UI should be taken from the messages.properties in the s&r UI module. You can leave the hardcoded stuff in the fxml files, but the text values should be set in runtime and read from the properties file.

Messages for the log file need not be localized.

Also, I think "Restoring values multiplied by" should be "Restore values multiplied by". But you would need to confirm with a native English speaker, which I am not.

**Comment by dxmaxwell** [comment]
I like the new location. In terms of the label, I've been trying to think of a shorter (and more clear if possible), how about "Restore with scale"? I am a native speaker, but I wouldn't put too much faith in that.

**Comment by georgweiss** [comment]
Or maybe "Restore with factor"?

**Comment by dxmaxwell** [comment]
To me "scale" better implies multiplication (as "offset" implies addition). And I think users at FRIB want to use this feature to scale the beamline configuration for different types of beams.  But, I can certainly live with "factor", and perhaps it would be preferred by the broader community. @georgweiss  as the primary maintainer I think it is up to you, unless we get some more opinions.

**Comment by georgweiss** [comment]
Since I'm not a native English speaker: I fold.

**Comment by georgweiss** [comment]
I'm sorry, but "Restore with scale" is not in messages.properties. You can leave the hard coded value in fxml (makes it easier for SceneBuilder), but when UI is launched the label text should be taken from messages.properties.

**Comment by geniejhang** [comment]
Oh. I didn't realize that you're mentioning that one since I don't see any other labels are in messages.properties.
Just updated.

**Comment by georgweiss** [comment]
Yeah, I might have committed a sin or two myself :-). I will accept once CI passes.

FYI: I will be leaving for four weeks of vacation starting Monday. You should maybe ask for permission to merge, check with @kasemir or @shroffk .

**Pull request merged**
