### PR TITLE
Make Table Widget Render 1D arrays as 1-by-n VTable

### PR DESCRIPTION
**Pull request by daykin**
#2506 - 47f3b copies all elements manually, a8b76a wraps the data in a VTable. Let me know which you prefer and I will squash the other.

### CODE REVIEW

**Comment by kasemir** [comment]
I slightly prefer the second one which wraps the array into one column of a VTable, but just slightly.
It wraps the array without copying each element. It might actually work with string as well as number arrays.

On the other hand, the data is then copied from a VTable into a `List<List<String>>` anyway, and when you create the `List<List<String>>`  yourself, you can create it such that the array elements turn into columns, which I feel is the expected display for an array, one wide table with columns, and not one high table with just one columns.

**Comment by daykin** [comment]
> On the other hand, the data is then copied from a VTable into a List<List<String>> anyway

I must admit I didn't pay much attention to what is happening after wrapping to a VTable. My logic was "We get a list, wrap it into a VTable, and do whatever is already done with VTables". Giving it a second look, this could be done better.

>you can create it such that the array elements turn into columns, which I feel is the expected display for an array, one wide table with columns, and not one high table with just one columns

Maybe this is my Data Science background talking, but I tend to envision things as the opposite. The convention in, for example, R and Pandas, relational databases, etc. is to have each column be an attribute, and each row a specific instance of that attribute. Plus, if I'm passing in a 2,000 element list, it could quickly get clunky to scroll through an arbitrarily wide table.

**Comment by daykin** [comment]
Looking a bit deeper into this,  the underlying JFX representation is ultimately a `ObservableList<List<ObservableCellValue>>`, so I don't see an easy way to avoid, at some point, copying the data into a list of lists. Maybe it's pointless to wrap it in a VTable first. Stepping back a bit, could you help me understand the rationale for deep-copying all incoming data? Does it have to do with alerting listeners?

**Comment by kasemir** [comment]
The deep copy is there for two reasons:

Avoid changes to widget's value. If you 'get' the value and then change it, while the JFX widget is at the same time using it, who know what'll happen.

Next, if a script fetches the value, modifies it, then sets that as a new value, passing out a deep copy asserts that the 'new' value is indeed recognized as new. When referencing the old value and changing it, the widget would still overall have the same value reference and not notice the change.

**Comment by kasemir** [comment]
There is no need to be hit by a bus, in fact I'd advise against it.
But you may win the lottery, in which case it should be easy to pay somebody else to take over maintenance.
Thanks!

**Pull request merged**
