### PR TITLE
CSSTUDIO-1366 Maintain undo/redo stack after save

### PR DESCRIPTION
**Pull request by georgweiss**
#1638

### CODE REVIEW

**Comment by kasemir** [comment]
Does this distinguish between a 'redo' and a new change?
I.e. will it do this:

Save (counter=0), undo (-1), redo (0) -> End up clean

Save (counter=0), undo (-1), new change (1) -> End up dirty

**Comment by ralphlange** [comment]
Yes. Given an initial undo stack of e.g. 1000 elements, it will do:

Save (counter=0), undo (-1), redo (0) -> End up clean

Save (counter=0), undo (-1), new change (1001) -> End up dirty no matter

**Comment by ralphlange** [comment]
Sorry - my comment was about my last suggestion for the algorithm.

Commit 7ac89a7 above does what you originally suggested, which will break.

**Comment by kasemir** [comment]
Right. I agree with you that a counter can accomplish the task, but it needs to count differently for 'redo' and 'new action', which this PR doesn't seem to handle.

**Comment by ralphlange** [comment]
See discussion at https://github.com/ControlSystemStudio/phoebus/issues/1638 where I suggested a slightly different algorithm. (That matches my comment above.)

**Pull request merged**
