### PR TITLE
JDK17 and fixing the dependencies with vulnerabilities

### PR DESCRIPTION
**Pull request by shroffk**
I am getting javadoc warnings which break the build ( when building with docs.. which I think the CI is not doing )

should we just ignore them or fix them... they are all in the save and restore service

### CODE REVIEW

**Review by georgweiss — APPROVED** [review]

**Comment by shroffk** [comment]
@georgweiss I added some changes to ignore javadoc warnings **only** from the save and restore service. 
Initially, I tried to fix most of them but I think the warnings were a bit excessive... we can address them over time

**Comment by georgweiss** [comment]
@shroffk, I'll try to find time to fix them a.s.a.p.

**Comment by shroffk** [comment]
> @shroffk, I'll try to find time to fix them a.s.a.p.

I don't think this is that urgent.. no stress :)
I just wanted to make a note to explain why I disabled the javadoc check for the save-restore service

Plus, we might have to redo some of the doc when we implement the restore on the service anyway... this could be done as part of that project/effort

**Review by georgweiss — COMMENTED** [review]
Should we not update to JavaFX 21 while we're at it?

**Comment by shroffk** [comment]
yes,

I am just trying to make changes step by step to solve issues as they come along... but yes javaFX21 should be part of this change

**Review by georgweiss — COMMENTED** [review]
Also: thumbnail and linear meter modules specify 11 for maven compiler plugin. I think the properties in those pom files should simply be removed.

**Comment by kasemir** [comment]
>  yes javaFX21 should be part of this change

JFX21 removes GTK2. JFX20 still allows GTK2 or 3. In the discussion for #2638 that was seen as a possible reason to move only up to JFX20 for a while.

**Comment by shroffk** [comment]
It seemed like the main issues with GTK3 were not reproduceable. At least the rendering issues mentioned by ESS were resolved... I have not yet tested the crashing issues I experienced.

At the very least we can move to jfx 20... but it at some point we will have to bite the bullet and make the move

**Comment by shroffk** [comment]
I do not intend to merge this branch immediately... I am trying to have the jdk17 + javafx20/21 branch ready for people to test.
Once people have given the green light we will merge

**Comment by kasemir** [comment]
OK, let's try JFX21 then. Since it's really just one number a a top level file, a site that experiences issues can locally build w/ JFX20 to check if that helps.

**Comment by shroffk** [comment]
There is still the open question about jumping to JDK21 also...not sure what our plan should be

**Comment by georgweiss** [comment]
> right now I am confused why the test for save-restore-module are not using JDK17

Not sure how you conclude this...

**Comment by georgweiss** [comment]
@shroffk, please remove jacoco plugin in pom.

**Comment by georgweiss** [comment]
@shroffk, I'm currently fixing this. Please be patient, will update this PR.

**Comment by shroffk** [comment]
I am working on this too... removing the jacoco plugin from the service too

**Comment by georgweiss** [comment]
OK, but I would also fix the Javadoc stuff.

**Comment by shroffk** [comment]
> OK, but I would also fix the Javadoc stuff.

Brilliant, you should have permission to push to this branch.

**Comment by georgweiss** [comment]
@shroffk, I am unable to push to branch ```jdk-17```:

error: src refspec jdk-17 does not match any

**Comment by shroffk** [comment]
Can you check that you have the right upstream setup... this seems like a git issue

**Comment by georgweiss** [comment]
git push --set-upstream origin jdk-17
 
This fails...

**Comment by kasemir** [comment]
Where are we with this? Right now the maven build of master is broken:
```
git clone https://github.com/ControlSystemStudio/phoebus.git
cd phoebus
mvn  -DskipTests clean install
```
ends in
```
[INFO] ----------------< org.phoebus:service-save-and-restore >----------------
[INFO] Building service-save-and-restore 4.7.4-SNAPSHOT                 [89/89]
[INFO]   from services/save-and-restore/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ service-save-and-restore ---
...
[INFO] --- compiler:3.6.2:compile (default-compile) @ service-save-and-restore ---
...
[INFO] --- javadoc:3.0.1:jar (attach-javadocs) @ service-save-and-restore ---
[INFO] The goal 'org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:javadoc' has not been previously called for the module: 'org.phoebus:core-util:jar:4.7.4-SNAPSHOT'. Trying to invoke it...
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
[WARNING] Creating fake javadoc directory to prevent repeated invocations: /Users/...phoebus/core/util/target/apidocs
[ERROR] Error fetching link: /Users/.../phoebus/core/util/target/apidocs/package-list. Ignored it.
[ERROR] Error fetching link: /Users/.../phoebus/app/save-and-restore/model/target/apidocs/package-list. Ignored it.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for phoebus (parent) 4.7.4-SNAPSHOT:
[INFO] 
[INFO] phoebus (parent) ................................... SUCCESS [  0.185 s]
[INFO] dependencies ....................................... SUCCESS [  0.007 s]
...
[INFO] service-alarm-config-logger ........................ SUCCESS [  0.584 s]
[INFO] service-save-and-restore ........................... FAILURE [  4.864 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:33 min
[INFO] Finished at: 2024-02-09T09:17:56-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project service-save-and-restore: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - Loading source files for package org.phoebus.service.saveandrestore...
```

That's with
```
$ mvn -version
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: /Users/.../java/apache-maven
Java version: 20, vendor: Oracle Corporation, runtime: /Users/.../jdk-20.jdk/..
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "14.3", arch: "aarch64", family: "mac"
```

`ant clean run` of course works fine, but the README suggests we're all maven aficionados, so might as well keep that in a functional state.

**Comment by shroffk** [comment]
Yesterday at the monthly meeting all participants gave the greenlight for the move to JDK17

javafx21 will be part of a separate PR

**Comment by kasemir** [comment]
.. and it builds again, even with maven! What an excellent way to conclude the week!!

**Pull request merged**
