### PR TITLE
Add in doc source files after save restore pref file #2927 PR

### PR DESCRIPTION
**Pull request by tynanford**
I don't know how the documentation upload works but the online docs haven't updated after https://github.com/ControlSystemStudio/phoebus/pull/2927 

I didn't commit these files with this PR but maybe I should have?

### CODE REVIEW

**Comment by shroffk** [comment]
I think there is a problem here with the applications.rst and services.rst

these files should be empty and populated programmatically

**Comment by shroffk** [comment]
The files should be the following

```
Services
========

The following sections describe available services.


.. toctree::
   :maxdepth: 1

   services_links
```


```
Applications
============

The following sections describe details of specific application features.


.. toctree::
   :maxdepth: 1

   applications_links
```

**Comment by tynanford** [comment]
I had run `cd docs/ && make clean html` to generate the website locally for testing and these files in source got changed. Looks like the generation put everything in alphabetical order. For now I reverted the changes to those two files. 

It does seem like these files should not be version controlled since they are generated from `conf.py`

Maybe the main reason the online docs didn't update thought is that the readthedocs build is failing since September? And we need a .readthedocs.yaml file now?

https://readthedocs.org/projects/control-system-studio/builds/?page=4

https://blog.readthedocs.com/migrate-configuration-v2/

**Comment by shroffk** [comment]
Oh wow!! thanks for catching this @tynanford 
I see there is no alternative but to set up the required config file

**Comment by shroffk** [comment]
@tynanford why did you close this

**Comment by tynanford** [comment]
Oh sorry @shroffk I should have left a comment

 This PR is obsolete now since https://github.com/ControlSystemStudio/phoebus/pull/2929 removed this file from the repository (since it's auto-generated)

`docs/source/preference_properties.rst`

Good news is #2929 fixed the readthedocs and the save-and-restore preference settings are up to date - https://control-system-studio.readthedocs.io/en/latest/preference_properties.html#saveandrestore-client

**Pull request closed without merging**
