### PR TITLE
CSSTUDIO-1281 Customize position of Acknowledge menu item

### PR DESCRIPTION
**Pull request by georgweiss**
Users have asked to place the Acknowledge/Unacknowledge context menu items on top. This change supports that if preference org.phoebus.applications.alarm/menuitem_acknowledge_ontop is set to true (defaults to false).

### CODE REVIEW

**Comment by kasemir** [comment]
Since ack/un-ack is indeed a frequent operation, the user can also double-click on an alarm in the table to ack/un-ack.

**Comment by kasemir** [comment]
I'm fine with ack/unack on top, so making that the default and only option.
Note that this
```
menu_items.add(0, new UnAcknowledgeAction(model, active));
```
needs to be replaced by
```
menu_items.add(new UnAcknowledgeAction(model, acked));
```
since otherwise you can no longer un-acknowledge. Fixing that as well.

**Comment by shroffk** [comment]
> I'm fine with ack/unack on top, so making that the default and only option.

+1

**Comment by georgweiss** [comment]
OK, thanks.

**Pull request merged**
