### PR TITLE
#2026 improving alarm message logging and logging view

### PR DESCRIPTION
**Pull request by shroffk**

### CODE REVIEW

**Review by georgweiss — COMMENTED** [review]
Looks OK to me, except for the failing unit test.

**Comment by georgweiss** [comment]
You will need to merge commit df7b71da903ebbe47d39993380748b44ed6223e4 to fix the unit test.

**Comment by shroffk** [comment]
@kasemir @tanviash 
The elastic service logs the output of the "toString()" as the raw source. I don't think anything uses this field as yet.. but by formatting it as valid json it means it will be easier to parse it.
A prototype action is also added which retrieves the last config.

**Comment by kasemir** [comment]
OK on turning toString into toJSON, but maybe re-use one shared object mapper. Object mappers are comparably expensive, but they're fully thread-safe (https://stackoverflow.com/questions/18611565/how-do-i-correctly-reuse-jackson-objectmapper/18615839), so you can create one once and then use it in all those places where you now have yet another object mapper.

**Comment by shroffk** [comment]
Yes, I like Object mappers cause of them being thread safe.
Since they are expensive.
Currently, the AlarmStateMessage, AlarmConfigMessage, and the generic AlarmMessage use the same object mappers.
`AlarmMessage.objectConfigMapper.writeValueAsString(this);`

The rest have a single static one for each of the message classes...but I can further consolidate them.

**Comment by shroffk** [comment]
@kasemir thanks... when I did a second review it made perfect sense to just combine the mapper into the 3 types I need.
I have made the corresponding changes

**Pull request merged**
