### PR TITLE
Replace Jackson to Gson for de/serializing Json

### PR DESCRIPTION
**Pull request by geniejhang**
- For save&restore client
- Update epicsCoreJava package version accordingly

### CODE REVIEW

**Comment by geniejhang** [comment]
@georgweiss Please review the change.

**Comment by georgweiss** [comment]
It looks as this replaces Jackson only on the client side. Save & restore service will still use Jackson do deserialize. If there is a performance gain in switching to Gson, I'd prefer if we could make that switch also in the service.

**Comment by shroffk** [comment]
@georgweiss @geniejhang 
Should we merge this PR and open another one for the service

**Comment by geniejhang** [comment]
@georgweiss @shroffk 
The main focus of the change was to enhance the performance for saving information to DB.
bottle neck was the client part and service performance is always good no matter what number of PVs we try to store.
Amount of work needed to update the service to Gson support exceeds the gain we get.
I'll do it in the end, but the priority is quite low.

I suggest merge this one first which is significant amount of improvement.

**Pull request merged**
