### PR TITLE
Update elastic mappings

### PR DESCRIPTION
**Pull request by georgweiss**
This update is needed in order to better support search in save-and-restore.

Also included in this PR some documentation on how to do data migration from RDB -> Elastic

### CODE REVIEW

**Review by shroffk — APPROVED** [review]

**Comment by shroffk** [comment]
I am confused why the alarm colours in the ui preferences had to be added again.
Did I miss them in the old PR? I remember Kay mentioning this issue and I thought I had added them as defaults.

In anycase this should fix the missing defaults too then

**Comment by kasemir** [comment]
I think it's not adding the ui preferences but the `docs/source/preference_properties.rst` documentation that lists them.
In previous PRs we updated the prefs but not the auto-generated docs.

**Comment by shroffk** [comment]
Ahh!!!
Ok, I think I have lost the ability pay attention to details...

**Comment by kasemir** [comment]
Since that part of the documentation is generated, we could exclude it from the repo (`.gitignore`)

**Comment by shroffk** [comment]
@georgweiss Just an FYI
now that the PV's and readbackPV's are not keywords and instead text...the default tokenizer will split the PV names which have any of the special char's :{}<> etc... which will impact how searching works especially if you are searching for complete PV names

**Comment by georgweiss** [comment]
Hmmm, as colon is used quite extensively we should maybe reconsider to revert back to keyword? But then users might complain why search on PV name will fail unless the proper case is used. Right?

**Comment by shroffk** [comment]
You can update the elastic search code to be case insensitive 
like this in ChannelFinder
https://github.com/ChannelFinder/ChannelFinderService/blob/70846a2244cc88d799d3ac8927eac0801c4bc20a/src/main/java/org/phoebus/channelfinder/ChannelRepository.java#L412

**Comment by georgweiss** [comment]
OK, so I suggest I revert back to keyword and add the channel finder strategy. Expect a PR soon.

**Pull request merged**
