### PR TITLE
Allow for building the core-pva module with jdk8

### PR DESCRIPTION
**Pull request by shroffk**
DO NOT MERGE

testing support for jdk8 core-pva builds using maven

### CODE REVIEW

**Comment by kasemir** [comment]
With JCA, wasn't there something network related in the JRE libs that's different between 8 and higher, so binaries built with 8 won't run in a higher JRE?
Maybe add a profile for use of JDK8 when building just core-pva, but otherwise use 11+ from the parent pom?

**Comment by shroffk** [comment]
I was trying to avoid a profile...with the above changes only the core-pva should be built with jdk11.

On my locally setup I was able to build the src but had issues with building the tst for core-pva using jdk8.

**Comment by shroffk** [comment]
@kasemir should we merge this?

**Comment by kasemir** [comment]
You wrote about issues with tests. Does it otherwise build and run?

**Comment by shroffk** [comment]
I does so long as you build without tests ( this means you don't just skip the tests but instruct maven to not build the test classes either )

`mvn clean verify -Dmaven.test.skip`

**Comment by shroffk** [comment]
I have not seen any issues with the rest of the Phoebus build or runtime ( limited testing with local softIocPva )

**Comment by kasemir** [comment]
Go ahead then!

**Comment by georgweiss** [comment]
This change causes issues in IntelliJ: test classes NetworkTest and MulticastDemo fail to compile as they call methods not available in Java 1.8.  Apparently the source and target Java versions are considered when IntelliJ builds these test classes. 

A maven build under Java 1.8 will also fail.

**Comment by shroffk** [comment]
I did not check the IDE setups. Even with intellij I use the maven actions

For the maven build the key is to `-Dmaven.test.skip` with jdk8. I will double check

**Pull request merged**
