### PR TITLE
Issue #1493

### PR DESCRIPTION
**Pull request by shroffk**
A datasource for alarm pvs which connect to nodes and leafs of the alarm trees

alarm_datasource_pv
alarm_datasource

Documentation on usage:
https://github.com/ControlSystemStudio/phoebus/blob/Issue_1493/app/alarm/datasource/doc/index.rst

### CODE REVIEW

**Comment by georgweiss** [comment]
Will try it out a.s.a.p.

**Comment by shroffk** [comment]
@kasemir 
I have tried to add the appropriate build.xml and included this in the classpath and the main build.xml.
I also ran the ant build locally... it worked correctly... however I am not sure how to correctly configure the ${version}... other than that it builds with ant fine.

**Comment by georgweiss** [comment]
Reads work as documented. Will attempt writes next.

Just a thought: in the alarm tree/list context menu it would be useful to have "Copy path to clipboard". But maybe the context menu is crowded as it is...?

**Comment by shroffk** [comment]
> But maybe the context menu is crowded as it is...?

It is already crowded. I would wait till we have more feedback

**Comment by georgweiss** [comment]
Upon further testing I get NaN and widget border indicating connection issue (?). Alarm service is local and alarm table/tree looks OK, so... Will investigate.

**Comment by shroffk** [comment]
Writing ack, unack can be done via a toggled button widget...
Can I merge this and we can work on the details with newer PRs

**Comment by georgweiss** [comment]
Sure, go ahead and merge.

**Pull request merged**
