### PR TITLE
AlarmLogTable: sets a TimestampedPV as selection and uses the

### PR DESCRIPTION
**Pull request by shroffk**
contextmenu helper to populate the context menu

### CODE REVIEW

**Comment by shroffk** [comment]
@georgweiss can you test this if you can..

**Review by georgweiss — COMMENTED** [review]
Not sure what I am supposed to see... With the huge indexes we have there might be a timeout issue. Only item I get in the context menu is "Configuration info"...

**Comment by shroffk** [comment]
This actions uses the selection and thus does not need to query... just used the items that are already in the table.

It should look as follows
image

**Comment by georgweiss** [comment]
Thing missing is the service definition file. Once in place all works as expected.

**Pull request merged**
