### PR TITLE
Katysaintin cssstudio 2090

### PR DESCRIPTION
**Pull request by katysaintin**
Here a pull request to replace TextField by a TextArea see issue #2090

### CODE REVIEW

**Comment by kasemir** [comment]
It's basically a 2 line change, but the PR seems to change the line endings, so it turns into a ~700 line update.
Typically, git handles the line ending variations between linux, windows, mac, so something's not quite right.

**Comment by katysaintin** [comment]
> It's basically a 2 line change, but the PR seems to change the line endings, so it turns into a ~700 line update. Typically, git handles the line ending variations between linux, windows, mac, so something's not quite right.

Yes sorry, probably , I have save action that format all the file (space and indentation). Do you want me to push the file again only the modified line ?

**Comment by kasemir** [comment]
Much preferred, yes. Thank you!

**Comment by katysaintin** [comment]
The 2 lines are : Line 45 for AddComponentAction  and Line 113 for AutocompleteMenu

**Comment by katysaintin** [comment]
> Much preferred, yes. Thank you!

OK

**Comment by katysaintin** [comment]
I make a new pull request only 2 lines are modified

**Pull request closed without merging**
