### PR TITLE
Split core-pv module into several modules

### PR DESCRIPTION
**Pull request by smarsching**
As discussed in #2939, this PR splits the `core-pv` module into several modules. The core classes for the PV support layer and the “internal” sources remain in `core-pv` and the control-system specific classes are split off into five new modules:

- core-pv-ca
- core-pv-mqtt
- core-pv-opva
- core-pv-pva
- core-pv-tango

The example Phoebus product now has explicit dependencies on all these modules, so that it offers the same range of PV sources that it offered before this change was made.

As a side effect of this change, a few small changes had to be made in other parts of the code base:

**app/databrowser**

- A dependency on `org.epics:epics-util` was added because this module is not included trasitively any longer.
- A new class `ChannelAccessStatusUtil` was added, so that the class `gov.aps.jca.dbr.Status` from the JCA library is not needed any longer. The JCA library was only used to translated numeric CA status IDs to string. Adding a dependency on the full library (which due to the Channel Access PV souce now being optional is not included transitively any longer) just in order to translate 22 possible integer values to strings seemed a bit excessive, so adding a simple utility class doing the translation seemed like the better option.

**app/display/representation-javafx** 

This module needs Apache Commons Lang 3. Before, this dependency was included transitively, now it is declared explicitly.

### CODE REVIEW

**Review by kasemir — APPROVED** [review]
Seems fine.
Importantly, while the preference files moved, their package names remained the same, so no changes to preference settings.
Once merged, I can update the ant build files.

**Comment by shroffk** [comment]
you will need to add the core-pv-xx to the services. 
alarm-server
save-restore
archive-engine
scan-server

I would include ca and pva

**Comment by shroffk** [comment]
At the very least they will have to be testing dependencies.

**Comment by smarsching** [comment]
@shroffk As far as I can tell, the save-restore service does not seem to depend on the PV layer at all (it does not depend on `core-pv`, neither directly nor transitively), so I do not think that dependencies have to be added there.

For the other servies (alarm-server, archive-engine, scan-server), I added all the PV modules as dependencies. At the moment, the modules for these services represent the “product”, so I think that they should include all the supported PV sources.

If you agree, I would still like to split these services into a “code” and a “product” part. The existing modules would become the product and the Java code would be moved into a “-core” module for each service (e.g. `alarm-server-core`). This way, users could easily built their own products for these services, adding or removing dependencies as needed. However, I think that this should be done in a separate PR because it is not closely related to the changes made in this PR.

**Comment by shroffk** [comment]
@smarsching you are right currently there is no core-pv required by save and restore. There is a PR which will soon be opened to add this feature of performing the restore operation from service... at which point we will need to add `core-pv` and the datasource implementations as pom dependencies.

In the long run we can explore the splitting of the service code into "core" and "product" packaging... we are doing this for services like Phoebus-Olog and ChannelFinder which allow sites to plug in processors and notifiers via SPI. Currenlty, this would be overkill for these services.
Let us start with including the broadly required DS (ca, pva, sim, loc)

**Comment by smarsching** [comment]
@shroffk As requested I removed the support for `mqtt`, `opva`, and `tga` / `tgc` from the services, only leaving `ca`, `pva`, and the internal ones (`sim`, `eq`, `loc`, etc.).

**Comment by shroffk** [comment]
@georgweiss @kasemir @tynanford @tanviash 
I am fine with merging this. If you have repackaged any of the services and need to support the additional datasources like tango/mqtt you will have to ensure they are explicitly added.

**Comment by georgweiss** [comment]
No objections.

**Comment by tynanford** [comment]
Fine with me. This might require an update to PVWS pom.xml file?

**Comment by kasemir** [comment]
> This might require an update to PVWS pom.xml file?

Does that mean we first need a "release" to get the new core-pv-* published for the PVWS build to find them?

**Comment by tynanford** [comment]
oh yeah, nevermind. It doesn't matter until we release this and update PVWS core-pv above 4.7.3. Something to remember down the road

**Comment by kasemir** [comment]
Still, if you have time it would be great to check a local build of the core-pv-*SNAPSHOTs and use that with PVWS, which ideally should work, but who knows.

**Comment by shroffk** [comment]
As you mention, we just need to keep this mind when do a release. We will update the dependencies of PVWS then.

**Comment by tynanford** [comment]
> Still, if you have time it would be great to check a local build of the core-pv-*SNAPSHOTs and use that with PVWS, which ideally should work, but who knows.

PVWS seems to work fine! At least with the pva, ca, sim, and sys PV types.

Also even in the startup logs for PVWS you can see things change based on what's included in the pom. For instance, only including core-pv-ca in pom shows this:

`pvws  | 2024-02-21 20:09:56 INFO [pvws.ws] Supported PV types: [loc, sim, sys, eq, ca]`

While including core-pv-ca, core-pv-pva, and core-pv-tango shows:

`pvws  | 2024-02-21 20:07:14 INFO [pvws.ws] Supported PV types: [loc, tgc, sim, sys, eq, ca, tga]`

**Comment by kasemir** [comment]
Thanks for checking that out!

**Pull request merged**
