### PR TITLE
Phoebus Olog - Use Group icon instead of color

### PR DESCRIPTION
**Pull request by cjenkscybercom**
style: indicate group / conversation status of search results in olog via icon instead of color.
This is to match the style changes in the web client

### CODE REVIEW

**Comment by cjenkscybercom** [comment]
Hmm...Not sure why ServerClientTest#testSinglePV would have failed?

**Comment by kasemir** [comment]
Did you figure out what exactly failed in ServerClientTest?
Once #2500 no longer showed errors, I merged it and then got a notification for an after-merge test failure.
Test runs fine when I run it locally, but something in there must be fragile.

**Review by georgweiss — APPROVED** [review]

**Comment by cjenkscybercom** [comment]
> Did you figure out what exactly failed in ServerClientTest? Once #2500 no longer showed errors, I merged it and then got a notification for an after-merge test failure. Test runs fine when I run it locally, but something in there must be fragile.

I could take a look, but it'd probably be better for whoever was working on it last to take a look. I also have other priorities taking precedence at the moment, so I wouldn't get to it for a while.

**Comment by georgweiss** [comment]
I'm seeing the same failure for a different PR. To me it looks like the test cases have some hard coded timeouts that may be too short when tests run in Github.

Will ask developer to reconsider/revisit the failing test case.

**Pull request merged**
