### PR TITLE
Display Editor: better visual recognition of widgets with macros usin…

### PR DESCRIPTION
**Pull request by pavel-ch**
…g an additional icon in the Editor Widget Tree
See #679

### CODE REVIEW

**Review by kasemir — APPROVED** [review]
Looks reasonable.
Just one thing, can you change the icon name from `money_dollar` to something more descriptive of its meaning? Like `macro_hint` or `macro_indicator` or `macro` or ..? Icon itself is fine, `$` is indeed used to insert macros.

**Comment by pavel-ch** [comment]
Good point, icon renamed. Thanks for comment.

**Comment by kasemir** [comment]
Thanks!
Now GitHub suggests that this PR includes a change to the ApplianceArchiveReaderFactory which I think should already be in place?!

**Comment by pavel-ch** [comment]
Hmm I see. I merged unnecessary by mistake phoebus/master into my fork. Anyway, there should not be any other changes than my own. Strange.

**Comment by kasemir** [comment]
I'm frankly unsure how to proceed. Simply merge, and the change to the ApplianceArchiveReaderFactory will be ignored? Or will the merge fail? Or will it require a follow-up PR to reset the ApplianceArchiveReaderFactory?

**Comment by pavel-ch** [comment]
I am afraid of git. I do it again and better. I delete my fork, create a new one and PR again.

**Comment by kasemir** [comment]
Sorry for this hassle, and thank you so much for trying again!

**Pull request closed without merging**
