### PR TITLE
documentation update : services architecture update + added troubeshooting

### PR DESCRIPTION
**Pull request by lcaouen**
[documentation update : services architecture update + added troubesho](https://github.com/ControlSystemStudio/phoebus/commit/4b7035c456212cf86c7d5703eae7406a9db00cb7)

### CODE REVIEW

**Review by georgweiss — COMMENTED** [review]
Actually the sections on JavaFX issues to me look a bit site specific. If Phoebus is built on same OS as target, the correct JavaFX libraries are included in the product tar.gz (or zip) file. 

It is also possible to do a cross-build by specifying -Djavafx.platform=\<os\> on the Maven command line, where os is linux, win or mac.

**Comment by lcaouen** [comment]
We had the problem beacause we build Phoebus under windows and we deloy it on linux and windows.
However, if you think it's too specific, I can remove the section.

**Comment by georgweiss** [comment]
Yes I think it is a bit too specific.

Again, if you need to build for both linux and win you can do that on Windows using -Djavafx.platform, but those would be two separate builds and two separate packages.

**Comment by georgweiss** [comment]
Maybe you can add the option to do cross-builds to the troubleshooting?

**Review by georgweiss — APPROVED** [review]

**Pull request merged**
