### PR TITLE
Display Builder Editor: New Selected Widget Distribution actions

### PR DESCRIPTION
**Pull request by pavel-ch**
... with predefined Gap. See #679

### CODE REVIEW

**Comment by kasemir** [comment]
When the gap is zero, would the result be the same as before?
I'd like to avoid adding too many options, so maybe remove/replace the original gap options, i.e. always prompt for a gap.

**Comment by pavel-ch** [comment]
No, this moves all widgets including the last one, and sets an equal gap between all. If the gap is 0, then widgets are back-to-back, if negative, they can overlap. The function does not work like the existing one, that is why I did not modify it. I think both variants have their use cases, and I would propose to distinguish between variants at the Distribution menu level.

**Comment by pavel-ch** [comment]
This new functions are specifically good when all widgets should fit into the display grid, which is hard to achieve in practice with original functions.

**Comment by kasemir** [comment]
OK, thanks!

**Pull request merged**
