### PR TITLE
Handle runtime width and height change in Poly* widgets

### PR DESCRIPTION
**Pull request by krisztianloki**
Polygone and Polyline widgets didn't handle width and height changes during runtime. With this PR they do.
I've decided not to override `defineProperties` in `PolyBaseWidget` but to add a separate function to keep the order of properties when saving the widgets.

### CODE REVIEW

**Comment by kasemir** [comment]
I'd be OK with changing the order, i.e. basically points 'first', since they're common to Polygon & line, then specializations later. Pick what's cleaner in the code.

**Comment by krisztianloki** [comment]
Overriding `defineProperties` is definitely cleaner. I'll update the code.

**Comment by pavel-ch** [comment]
Trying to create polyline or polygon in Editor: points are outside the widget area and inconsistent with mouse clicks in editor. Also after widget resize, the points are out of sync with handles in editor, see:
image
Reproducible on Windows.
I use a site specific copy of the original implementation of polyline widget due to some added features (two-color line) and this original code works just fine in this regard.
Please look at it or revert, thank you.

**Comment by krisztianloki** [comment]
You are right @pavel-ch, I've just opened a PR to fix this: #1473

**Pull request merged**
