### PR TITLE
CSSTUDIO-1023 Added PVList column to show PV value

### PR DESCRIPTION
**Pull request by georgweiss**
As requested by our users.
Also tweaked the width of the columns in the table.
Screenshot 2020-09-23 at 15 47 50

### CODE REVIEW

**Comment by kasemir** [comment]
For the value column, please check that it doesn't crash when trying to show a 1MSample array value.

**Comment by georgweiss** [comment]
I'd say the same concern should apply to WidgetInfoDialog, right?

**Comment by kasemir** [comment]
Exactly, that's why it includes code to only show the type, not the full value, see
https://github.com/ControlSystemStudio/phoebus/blob/master/app/display/representation-javafx/src/main/java/org/csstudio/display/builder/representation/javafx/WidgetInfoDialog.java#L179

**Comment by georgweiss** [comment]
To be frank I cannot see the difference in the implementations, save for PVList not calling VTypeUtil.

**Pull request merged**
