### PR TITLE
Save & Restore: Setting threshold for highlighting PVs by their delta values

### PR DESCRIPTION
**Pull request by geniejhang**
@georgweiss I found threshold setting method is commented out.
So, I uncommented and implemented corresponding UI as below.

Delta cells are highlighted only when they're above delta threshold.
I also put the percentage number next to the absolute value.

### CODE REVIEW

**Comment by georgweiss** [comment]
I do not quite understand the screen shots. Why is the delta live setpoint not highlighted in the second screen shot?

**Comment by geniejhang** [comment]
Because it didn’t pass the Delta threshold. 21.66% is within 22%

**Comment by georgweiss** [comment]
Of course, my bad. Sorry.
Appreciate you are working on this, the code was commented out as I did not consider it essential for an initial release of S&R. 
In any case, did the commented out code include the percentage indication next to the value? I'm asking since I think the percentage indication impacts the readability. After all, calculating the difference in percent is not that hard...

**Comment by geniejhang** [comment]
No. Commented out part only sets the threshold values. Percentage part I added. I can make it optional if you like.

**Comment by georgweiss** [comment]
Yes, please make it optional, e.g. a checkbox or other UI item to toggle between show/hide.

**Comment by geniejhang** [comment]
Got it. Toggle button sounds good to me. 
I’ll do it tomorrow since it’s 3 am now.
I was fighting with a bat intruded in my house.

**Comment by geniejhang** [comment]
@georgweiss Now it has toggle button at the top.

**Comment by ralphlange** [comment]
Looking at the pretty screenshot...
Is there a Phoebus policy for labeling toggle buttons?
I.e.: Does the label show the current state, or does it show what happens when you press the button?
(Personally, I am afraid of clicking on any toggle button exactly because of that question.)

**Comment by kasemir** [comment]
When a button is both 'indicator', it can indeed be confusing. Does it show what you'll get, or what you have now?
For the alarm table's "maintenance mode" button, the tool tip explains what you have and what you'll get, and I think in general a tool tip can be a good option to handle this.

**Comment by geniejhang** [comment]
@georgweiss Any comments?

**Comment by georgweiss** [comment]
On top of the tooltip, the pressed state of the button should show percentage. Otherwise no comments.

**Comment by geniejhang** [comment]
Changed to "If pressed, show \u0394 percentage when PV has non-zero \u0394"

**Pull request merged**
