### PR TITLE
#2879 error dialog with the message text extracted from the stacktrace

### PR DESCRIPTION
**Pull request by shroffk**
#2879

### CODE REVIEW

**Review by kasemir — APPROVED** [review]

**Comment by kasemir** [comment]
The reformatting is good.
One more thing: For some exceptions, `getMessage()` returns `null`.
That's part of why we should always `Logger.getLogger(..).log(Level.XXX, "Trouble at mill!", the_exception)` and not `...the_exception.getMessage()`. The exception has the full stack trace, line number etc., while `getMessage()`  could just be `null`.
For the dialog, the "Detail" section will always have the full information, which is great.
For exceptions that hold a message, this new end-user summary of message.. cause[1] ... is even better.
Not sure if there's a good way to improve on "null Cause[1] null Cause[2] null".
If getMessage returns null, print the exception class name? "InvalidArgumentException Cause[1] ..."??

**Comment by shroffk** [comment]
When the message is null then the class name is printed (broadly useful... some exception class names are quite self explanatory)

image


Also,

I think we should have a flag `append_ex_stacktrace_messages`  to allow user to add their own **first line** of message followed by the above abbreviated stack trace messages

Unable to retrieve log entries <-- user message

Olog search failed                   <-- first ex message
[1] Connection timeout           <-- summary of stack trace messages
[2] No host with name....

**Comment by kasemir** [comment]
Excellent! Users will now look forward to seeing errors because they're so exquisitely formatted!!!
We should add some online help: If you don't see any errors and miss the dialog, here's how you can cause some trouble...

**Comment by kasemir** [comment]
This is really good! No more need to ask users to open the details and scroll to the bottom because that's where the actual cause can be found..

**Comment by shroffk** [comment]
@kasemir I ready to merge this... any objections :)

**Comment by kasemir** [comment]
I'm happy about it.

**Pull request merged**
