### PR TITLE
CSSTUDIO-2046 Bugfixes: decode escaped characters in URIs in two places.

### PR DESCRIPTION
**Pull request by abrahamwolk**
This PR adds decoding of escaped characters in URIs to:
1. The constructor of `DisplayInfo`. As a consequence, Phoebus is able to locate already-opened instances of OPIs that contain spaces in their filenames.
2. The method `DockItemWithInput.setInput()`, so that tool-tips of tabs containing instances of `DockItemWithInput` don't contain escaped characters.

### CODE REVIEW

**Review by georgweiss — APPROVED** [review]

**Review by kasemir — APPROVED** [review]
Well, the thing is that 6 years ago we changed from getRawPath() to getPath() to "Preserve '%20' encoding of space in file name", 
c173ee58140b11e291debe1967fc099b6d7515f5
Maybe this is change is good for another 6 years?

**Comment by abrahamwolk** [comment]
> Well, the thing is that 6 years ago we changed from getRawPath() to getPath() to "Preserve '%20' encoding of space in file name", [c173ee5](https://github.com/ControlSystemStudio/phoebus/commit/c173ee58140b11e291debe1967fc099b6d7515f5) Maybe this is change is good for another 6 years?

I am not familiar with the intention of that commit; do you think that the issue that commit fixed will re-emerge with the changes in this PR?

**Comment by kasemir** [comment]
I don't know. 6 years ago, the fix for spaces in filenames was the exact opposite of what you do now, but some other details have changed over that time. I'm fine with merging this, and if new issues arise, you'll fix them as they become clearer. Simply avoiding spaces in file names will of course always work.

**Comment by abrahamwolk** [comment]
Alright!

**Pull request merged**
