### PR TITLE
Update to Boolean Button: confirmation dialog only for toggle mode

### PR DESCRIPTION
**Pull request by georgweiss**
This is for #2423.

An error dialog is launched "close" to the Boolean Button widget if user selects an unsupported combination of mode and confirmation dialog.

### CODE REVIEW

**Comment by kasemir** [comment]
At first glance I'm missing some construct including `if (toolkit.isEditMode())`.
Will this always open a dialog, including in run mode?
It seems best to limit the dialog to edit mode.

**Comment by georgweiss** [comment]
> At first glance I'm missing some construct including `if (toolkit.isEditMode())`. Will this always open a dialog, including in run mode? It seems best to limit the dialog to edit mode.

Well, since I assume that a change in mode or confirmation dialog properties happens only in edit mode, a check should not be needed.

**Review by kasemir — APPROVED** [review]

**Comment by kasemir** [comment]
Turns out the new listener addition and removal don't match:
```
model_widget.propConfirmDialog().addPropertyListener(confirmDialogWidgetPropertyListener);
```
vs
```
model_widget.propMode().removePropertyListener(confirmDialogWidgetPropertyListener);
```

Need to remove from `propConfirmDialog()` where it was added.

Symptom is runtime error
```
 SEVERE ... Unknown listener
... at org.csstudio.display.builder.representation.javafx.widgets.BoolButtonRepresentation.unregisterListeners(BoolButtonRepresentation.java:226)
```

**Comment by georgweiss** [comment]
My bad, slipped on the keyboard. Thanks @kasemir.

**Pull request merged**
