### PR TITLE
Add EPICS Jackie PV source

### PR DESCRIPTION
**Pull request by smarsching**
This PR adds a PV source that uses [EPICS Jackie](https://oss.aquenos.com/epics/jackie/), an alternative Java implementation of the Channel Access protocol. The new PV source uses the `jackie://` prefix and can thus coexist with the existing `ca://` PV source.

### CODE REVIEW

**Review by kasemir — APPROVED** [review]

**Comment by kasemir** [comment]
Does EPICS jackie come with a public git repo? On https://oss.aquenos.com/epics/jackie/ I see downloads of source snapshots, but nothing like a git repo for issue tracking, pull requests etc.

**Comment by smarsching** [comment]
The Git repo is at https://gitlab.aquenos.com/oss/epics/epics-jackie/.

**Comment by kasemir** [comment]
Perfect, thanks!

**Comment by smarsching** [comment]
I didn’t know about that one. It seems like it was started around the same time that I started working EPICS Jackie, so I guess that’s how I missed it.

Due to its GPL license, it would not be possible to integrate it into Phoebus though (GPL and EPL are incompatible as far as I know).

**Comment by kasemir** [comment]
Not sure about user base. Last commit was 4 years ago

**Pull request merged**
