### PR TITLE
#1714 logbook applications

### PR DESCRIPTION
**Pull request by shroffk**
Work In Progress - do not merge

### CODE REVIEW

**Review by georgweiss — COMMENTED** [review]
Not sure I understand lines like:
.....setMaxWidth(1f * Integer.MAX_VALUE * 40);

**Comment by georgweiss** [comment]
When a an attribute of a property has been selected and switched to edit mode (but not edited), the cell remains visible when the property is collapsed. When the property is expanded, the cell in question contains the (unedited) value twice.
Screen shots attached.
Screenshot 2021-02-09 at 14 19 52
Screenshot 2021-02-09 at 14 19 58
Screenshot 2021-02-09 at 14 20 08

**Comment by shroffk** [comment]
I have fixed the editing

**Comment by georgweiss** [comment]
@shroffk, I'm afraid there is a mismatch in the data model in regards to properties. The client will construct a HashMap of properties, while the server expects a Set.
I would expect a change on the server is preferable, let me know if you need me to do it.

**Comment by shroffk** [comment]
Ok I think this PR is getting quite big.
We can merge this at this point.
- new ui for creating olog entires
- new SPI to auto contribute properties
- move common dialogs to core-ui

**Comment by georgweiss** [comment]
Go ahead.

**Comment by georgweiss** [comment]
@shroffk , can I go ahead and add my stuff (mainly embedded images)?

**Comment by shroffk** [comment]
Ok, go ahead
will you be editing the create log entry dialog  or the table viewer?

**Comment by georgweiss** [comment]
Only Edit dialog to add button for emedded images.

**Pull request merged**
