### PR TITLE
#1714

### PR DESCRIPTION
**Pull request by shroffk**

### CODE REVIEW

**Review by georgweiss — COMMENTED** [review]
Is this correct:
`default_logbook_query=*&start=12 hours&end=now`
I would assume 
`default_logbook_query=desc=*&start=12 hours&end=now`
But maybe I am missing something?

**Comment by shroffk** [comment]
> Is this correct:
> `default_logbook_query=*&start=12 hours&end=now`
> I would assume
> `default_logbook_query=desc=*&start=12 hours&end=now`
> But maybe I am missing something?

done

**Comment by georgweiss** [comment]
Since we decided to support Commonmark for OlogES I have come to realize that the delta to legacy Olog is quite substantial. Should not the new module be targeting Olog ES only?

**Comment by shroffk** [comment]
> Since we decided to support Commonmark for OlogES I have come to realize that the delta to legacy Olog is quite substantial. Should not the new module be targeting Olog ES only?

Yes that will be the case.
However I do not want to make too many modules and confusion. 
The final product can choose 
1. old olog client and the general ui 
or
2. olog-es client and new olog ui

**Comment by georgweiss** [comment]
Fine, but should not the added module be named accordingly, e.g. ui-es/app-logbook-olog-es-ui?

**Comment by shroffk** [comment]
> Fine, but should not the added module be named accordingly, e.g. ui-es/app-logbook-olog-es-ui?

Well, the -es is a placeholder till we completely deprecate and remove the old olog.
I hope that in 1-2 years -es will not be needed

**Comment by georgweiss** [comment]
That's OK as long as we agree that the added module targets Olog ES and nothing else.
However, there is still an "asymmetry" since we have client/client-es

**Pull request merged**
