### PR TITLE
new organization of olog modules

### PR DESCRIPTION
**Pull request by shroffk**
includes moving the old and new client into a common parent module called olog #1654

### CODE REVIEW

**Comment by georgweiss** [comment]
I'm afraid that in the restructured olog* modules package structure in `src` is incorrect, root is `phoebus` instead of `org`.
Also, while we're at it, could we consider renaming the XML* classes in olog-es, and optionally remove XML annotations? Suggest we do:
XmlLog -> LogEntry
XmlLogbook -> Logbook
XmlTag -> Tag
XmlAttachment -> Attachment
XmlProperty -> Property
I'd also propose we put these classes in a "model" sub-package.

**Comment by shroffk** [comment]
Sorry I am working with intellij and was trying to do a refactor with a git move which would preserve history... not sure what I did wrong.
I will fix it and do the rename too.

**Comment by shroffk** [comment]
The rename can't be exactly as you described since the interfaces share the same name. I would like to recommend 
OlogLog
OlogTag
....

**Comment by shroffk** [comment]
Ok, 
I also used this as an opportunity to do a bit of cleanup. There was some reclics of the copy paste from the old olog which needed to be removed.

**Comment by georgweiss** [comment]
Hmm, do we need the @Xml* annotations?

**Comment by shroffk** [comment]
I think the annotations are used by fasterxml... maybe we should expand the serialization and deserialization tests. 
For the time being can we close this PR.

**Review by georgweiss — APPROVED** [review]

**Pull request merged**
