### PR TITLE
#1909 initialize logbook table and calendar using preferences

### PR DESCRIPTION
**Pull request by shroffk**
#1909

### CODE REVIEW

**Review by georgweiss — COMMENTED** [review]
This does not actually solve my issue: if user removes desc=* from search string, it is put back after restart. It's difficult to explain why other modifications to the search string are maintained between restarts, but not removal of desc=*.

**Comment by shroffk** [comment]
> This does not actually solve my issue: if user removes desc=* from search string, it is put back after restart. It's difficult to explain why other modifications to the search string are maintained between restarts, but not removal of desc=*.

I can't recreate this... 
removing desc=* and only keeping the start and end time in the query.. upon restart results in only the start and end being present.

**Comment by georgweiss** [comment]
> > This does not actually solve my issue: if user removes desc=* from search string, it is put back after restart. It's difficult to explain why other modifications to the search string are maintained between restarts, but not removal of desc=*.
> 
> I can't recreate this...
> removing desc=* and only keeping the start and end time in the query.. upon restart results in only the start and end being present.

Using a default search string that includes desc=* will add it. But maybe your point is to remove desc=* from the default in the preferences?

**Comment by shroffk** [comment]
removing from the default preference is one part.

but if you open the log table... changed the query to a non empty query... then exit/restart phoebus... the modified query should be restored from momentos

**Comment by georgweiss** [comment]
> removing from the default preference is one part.
> 
> but if you open the log table... changed the query to a non empty query... then exit/restart phoebus... the modified query should be restored from momentos

Sorry, that is not the case in my test. The default query is not overridden, so desc=*&start=12 hours&end=now. If I change 12 hours -> 120 hours, after restart I do indeed see 120 hours, but desc=* is still there even if I remove that portion before restart.

**Comment by shroffk** [comment]
Looking into this... keep this PR open

**Comment by shroffk** [comment]
Ok, 
I added a caching feature between relaunches of the log table. This is different from the momento which stores the last shutdown state.

**Comment by georgweiss** [comment]
Thanks, works as I expect now.

**Pull request merged**
